### ISSUE TITLE
Create Orders Models

### ISSUE THREAD

**Issue by bartconsedine** [CSCI-GA-2820-SP23-001/orders#11]

**Comment by bartconsedine** [comment]
**As a** Order Manager
**I need** the ability to execute CRUD API calls with modeled Order data
**So that** users can Create, Read, Update and Destroy order information
   
 ### Details and Assumptions
* Model Orders tables and associated table columns in the database and the types of data associate with each column

   
 ### Acceptance Criteria  
   
 ```gherkin
When models are in place, CRUD actions will be able to be performed by users with reliable data formatting 
```

**Comment by EmiliePourchet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-001-63ec3aa24307cc4b616dd7dd/issues/CSCI-GA-2820-SP23-001/orders/11?planning-poker) with Zenhub @bartconsedine @EmiliePourchet @LotteLa @marianaruizallende @nilesh1401 @Victoria-Obasa
