### ISSUE TITLE
Update the routes.py file to contain your Flask service routes

### ISSUE THREAD

**Issue by marianaruizallende** [CSCI-GA-2820-SP23-001/orders#12]
**As a** user
**I need to** be able query the API using unique URLs and methods
**So that**  I can perform CRUD tasks on that database
   
 ### Details and Assumptions
 * Database and appropriate models will be in place so that routes can be full functional
   
 ### Acceptance Criteria  
   
 ```gherkin
All API endpoints have been built out and validated to show they are are ready ready perform necessary CRUD tasks 
```

**Comment by EmiliePourchet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-001-63ec3aa24307cc4b616dd7dd/issues/CSCI-GA-2820-SP23-001/orders/12?planning-poker) with Zenhub @bartconsedine @EmiliePourchet @LotteLa @marianaruizallende @nilesh1401 @Victoria-Obasa
