### ISSUE TITLE
Create an Order

### ISSUE THREAD

**Issue by EmiliePourchet** [CSCI-GA-2820-SP23-001/orders#2]
**As a** Order Manager
**I need** the ability to create an order and have it write in my orders database 
**So that** I can keep track of all orders and see order details as needed
   
 ### Details and Assumptions
* We assume the order details will contain the following: customer ID, at least one SKU, a quantity for each SKU, an original price for each SKU, total order price calculated by SUM(SKU price * Quantity) + tax
* We will store order details in a PostgreSQL database

   
 ### Acceptance Criteria  
   
 ```gherkin
Given the service is running
When I create an order
Then that order should exist in the database with all order details present
And an order ID should be assigned to each order and stored in the database
And time and date of order placement should be stored in the database
```

**Comment by marianaruizallende** [comment]
@emiliepourchet, maybe add this to the Acceptance criteria:

And each order lists a product, or multiple or none
And each order shows product quantity, 
And each order shows the selected product's original price
Each order calculates the Product's original price * quantity

**Comment by EmiliePourchet** [comment]
This ticket is just saying that an order that is created should be written into the orders database

Maybe we need another ticket to explain what information must be present when the order is created?

**Comment by EmiliePourchet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-001-63ec3aa24307cc4b616dd7dd/issues/CSCI-GA-2820-SP23-001/orders/2?planning-poker) with Zenhub @bartconsedine @EmiliePourchet @LotteLa @marianaruizallende @nilesh1401 @Victoria-Obasa
