### ISSUE TITLE
Create Orders Database

### ISSUE THREAD

**Issue by marianaruizallende** [CSCI-GA-2820-SP23-001/orders#4]
**As an** Order Manager
**I need** orders and/or order items to be saved in a database
**So that I can** identify and keep track of each customer's order, order contents

###Details and Assumptions
* Both an order model and an item model have to be created

###Acceptance Criteria
```gherkin
**When** an API call for an order or order item is made
**Then** models.py file will detail the structure of data tables to be created/used
```
Information to be collected in the database:
- name
- street
- city
- state
- postal code
- shipping price
- date created
- items (link to items table)

**Comment by EmiliePourchet** [comment]
I think this is similar to the create ticket I've already created which writes the order into the database. Perhaps we can turn this into a frontend ticket or the read ticket?

**Comment by EmiliePourchet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-001-63ec3aa24307cc4b616dd7dd/issues/CSCI-GA-2820-SP23-001/orders/4?planning-poker) with Zenhub @bartconsedine @marianaruizallende @LotteLa @Victoria-Obasa @nilesh1401 @EmiliePourchet

**Comment by EmiliePourchet** [comment]
Removed from Sprint 1 as this was done under the Create Models story. This separate story was not needed and should not impact burndown charts.
