### ISSUE TITLE
Create scenarios (feature file) for Create Order

### ISSUE THREAD

**Issue by Victoria-Obasa** [CSCI-GA-2820-SP23-001/orders#40]
**As a** creator of this service
**I need to** create scenarios in the feature and steps files
**So that**  I can perform BDD testing

### Assumption
* The UI already contains Create order functionality that can be tested

### Acceptance Criteria

 ```gherkin
 Given the scenarios for Create Order have been added
 When I test Create Order functionality on UI
 The test runs and passes
```

**Comment by EmiliePourchet** [comment]
Where is this requirement written in hwk 2?
