### ISSUE TITLE
Create scenarios (feature file and steps) for Read Order

### ISSUE THREAD

**Issue by nilesh1401** [CSCI-GA-2820-SP23-001/orders#48]
**As a** creator of this service
**I need to** create scenarios in the feature and steps files
**So that**  I can perform BDD testing

### Assumption
* The UI already contains Read order functionality that can be tested

### Acceptance Criteria

 ```gherkin
 Given the scenarios for Read Order have been added
 When I test Read Order functionality on UI
 The test runs and passes ```

**Comment by nilesh1401** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-001-63ec3aa24307cc4b616dd7dd/issues/CSCI-GA-2820-SP23-001/orders/48?planning-poker) with Zenhub @EmiliePourchet @bartconsedine @LotteLa @marianaruizallende @Victoria-Obasa @nilesh1401

**Comment by EmiliePourchet** [comment]
I think we need to stick to the homework as there is already a lot lot lot to do in there. Is this indicated as a requirement in hwk 2?
