### ISSUE TITLE
Deploy to Kubernetes cluster

### ISSUE THREAD

**Issue by LotteLa** [CSCI-GA-2820-SP23-001/orders#51]
**As an** Order Manager
**I need to** deploy our application to a Kubernetes cluster on IBM Cloud
**So that** I can gain better business agility and scale

**Assumptions**
• Allows for continuous delivery to be achieved
• Allows for creation of automated testing integrated with an automated CI/CD pipeline

**Acceptance Criteria**

1. devcontainer environment updated, IBM Cloud CLI downloaded and installed
2. Kubernetes metadata files created for deployment
3. Kubernetes CLI kubectl command used to deploy service to Kubernetes cluster
4. IP address of worker node retrieved and combined with port to go to service URL, working

Requirement 3: Deploy to the Cloud, Story 2/2

**Comment by LotteLa** [comment]
**As an** Order Manager
**I need to** deploy our application to a Kubernetes cluster on IBM Cloud
**So that I** can gain better business agility and scale

**Assumptions**
• Allows for continuous delivery to be achieved
• Allows for creation of automated testing integrated with an automated CI/CD pipeline

**Acceptance Criteria**

1. devcontainer environment updated, IBM Cloud CLI downloaded and installed
2. Kubernetes metadata files created for deployment
3. Kubernetes CLI _kubectl_ command used to deploy service to Kubernetes cluster 
4. IP address of worker node retrieved and combined with port to go to service URL, working

**Comment by EmiliePourchet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-001-63ec3aa24307cc4b616dd7dd/issues/CSCI-GA-2820-SP23-001/orders/51?planning-poker) with Zenhub @bartconsedine @EmiliePourchet @LotteLa @marianaruizallende @nilesh1401 @Victoria-Obasa

**Comment by marianaruizallende** [comment]
@EmiliePourchet I'm working ont his 
please do not move

**Comment by EmiliePourchet** [comment]
I moved it to sprint 3 for that very reason, I thought this is what we concluded during our last meeting
@marianaruizallende You can still pick this up as part of sprint 3 if you'd like to though!

**Comment by marianaruizallende** [comment]
ok I will, its already done, so I just need to connect the issue to this and the other story 
http://159.122.187.155:31001/
