### ISSUE TITLE
Read Orders

### ISSUE THREAD

**Issue by Victoria-Obasa** [CSCI-GA-2820-SP23-001/orders#6]
**As an** Order Manager
**I need to** make sure orders are read and saved to the database
**So that** orders can be searched through, fulfilled, modified, or deleted in the future

**Assumptions**
- Allows the search and retrieval of specific information in the database and reading their values
- Orders are written in language that can be read by the PostgreSQL
- Order details saved will contain a unique customer ID, quantity, and total price
- Promotions and customer information (name & address) will be applied

**Acceptance Criteria**
1. All details are included before adding to the database (unique customer ID, quantity and total price)
2. Order ID has all of the necessary details to be read and saved by the database
3. Orders can be translated to the requirements of the database

**Comment by EmiliePourchet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-001-63ec3aa24307cc4b616dd7dd/issues/CSCI-GA-2820-SP23-001/orders/6?planning-poker) with Zenhub @bartconsedine @EmiliePourchet @LotteLa @marianaruizallende @nilesh1401 @Victoria-Obasa
