### ISSUE TITLE
Update Order

### ISSUE THREAD

**Issue by nilesh1401** [CSCI-GA-2820-SP23-001/orders#7]
**As an** Order manager 
**I need** an option to modify the order 
**So that** we don't have to cancel the orders in case of minor modifications like change of address, payment method etc, 

**Details and Assumptions**
A Customer_ID will create an order in our e-commerce and after placing an order he/she might want to modify the order instead of cancelling and placing a new order 

**Assumptions:**

- The order modification should be minor and limited to details that would not affect the price and quantity of the products orders
- Order can be modified only within a specified time frame - typically few hours 
- The verification need to take place in order to ensure that the same customer is changing the order 
- The tax amount might change based on the location of the order 
- The inventory has to be verified in case of the address change 
- The delivery time might be updated if there is an address change 
- The payment settlement parties might be notified in case of change in payment method

**Acceptance Criteria:**

- The changes in the order should be reflected in real time in the current orders database
- The price , discounts and promotions should not change while updating an order 
- The customer ID should be verified before changing an order
- The time frame to modify an order should be clearly communicate to the customer 
- **Given the** the customer already placed an order,  **When** the customer requests an order update, TeamOrder will pull up the order details using a unique Order_ID and show the update options for the things that can be updated like  Payment method and Shipping Address

**Comment by EmiliePourchet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-001-63ec3aa24307cc4b616dd7dd/issues/CSCI-GA-2820-SP23-001/orders/7?planning-poker) with Zenhub @bartconsedine @EmiliePourchet @LotteLa @marianaruizallende @nilesh1401 @Victoria-Obasa
