### ISSUE TITLE
Create scenarios (feature file and steps) for Cancel order

### ISSUE THREAD

**Issue by EmiliePourchet** [CSCI-GA-2820-SP23-001/orders#79]
**As a** creator of this service
**I need to** create scenarios in the feature and steps files
**So that**  I can perform BDD testing

### Assumption
* The UI already contains cancel order functionality that can be tested

### Acceptance Criteria

 ```gherkin
 Given the scenarios for cancel Order have been added
 When I test Cancel Order functionality on UI
 The test runs and passes ```

**Comment by marianaruizallende** [comment]
@EmiliePourchet the pull request is assigned to you, however, I could not understand how to fix the merge conflict. I'll try to talk to druvh tomorrow
