### ISSUE TITLE
List Orders

### ISSUE THREAD

**Issue by Victoria-Obasa** [CSCI-GA-2820-SP23-001/orders#9]
**As an** Order Manager
**I need to** list out orders as an output
**So that** I can pull a record from the database based on unique properties

**Assumptions**
- Allows the search and retrieval of specific information in the database
- Order details saved will contain a unique customer ID, quantity, and total price
- Orders can be seen in order to be seen, itemized, or organized
- Orders are written in language that can be read by the PostgreSQL

**Acceptance Criteria**
1. All details are included before adding to the database (unique customer ID, quantity, total price, and customer information)
2. Order list has all of the necessary details to be read and saved by the database

**Comment by EmiliePourchet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-spring23-001-63ec3aa24307cc4b616dd7dd/issues/CSCI-GA-2820-SP23-001/orders/9?planning-poker) with Zenhub @bartconsedine @EmiliePourchet @LotteLa @marianaruizallende @nilesh1401 @Victoria-Obasa

**Comment by marianaruizallende** [comment]
@bartconsedine I'm getting an error test bc I have "no creat order" yet! 
I'll reach out to bart!
